/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { InclusiveDatesLabels } from "./components/inclusive-dates/inclusive-dates";
import { InclusiveDatesCalendarLabels, YearChangedEventDetails } from "./components/inclusive-dates-calendar/inclusive-dates-calendar";
import { ChronoOptions, ChronoParsedDateString } from "./utils/chrono-parser/chrono-parser.type";
import { InclusiveDatesCalendarLabels as InclusiveDatesCalendarLabels1, MonthChangedEventDetails, YearChangedEventDetails as YearChangedEventDetails1 } from "./components/inclusive-dates-calendar/inclusive-dates-calendar";
import { InclusiveTimesLabels } from "./components/inclusive-times/inclusive-times";
import { InclusivekTimesPickerLabels, TimeValue } from "./components/inclusive-times-picker/inclusive-times-picker";
export { InclusiveDatesLabels } from "./components/inclusive-dates/inclusive-dates";
export { InclusiveDatesCalendarLabels, YearChangedEventDetails } from "./components/inclusive-dates-calendar/inclusive-dates-calendar";
export { ChronoOptions, ChronoParsedDateString } from "./utils/chrono-parser/chrono-parser.type";
export { InclusiveDatesCalendarLabels as InclusiveDatesCalendarLabels1, MonthChangedEventDetails, YearChangedEventDetails as YearChangedEventDetails1 } from "./components/inclusive-dates-calendar/inclusive-dates-calendar";
export { InclusiveTimesLabels } from "./components/inclusive-times/inclusive-times";
export { InclusivekTimesPickerLabels, TimeValue } from "./components/inclusive-times-picker/inclusive-times-picker";
export namespace Components {
    interface InclusiveDates {
        "calendarButtonContent"?: string;
        /**
          * @default () =>     false
         */
        "disableDate": HTMLInclusiveDatesCalendarElement["disableDate"];
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default "inclusive-dates"
         */
        "elementClassName"?: string;
        /**
          * @default 1
         */
        "firstDayOfWeek"?: number;
        /**
          * @default "YYYY-MM-DD"
         */
        "format": string;
        /**
          * @default true
         */
        "formatInputOnAccept"?: boolean;
        /**
          * @default false
         */
        "hasError": boolean;
        "id": string;
        "inclusiveDatesCalendarLabels"?: InclusiveDatesCalendarLabels;
        /**
          * @default defaultLabels
         */
        "inclusiveDatesLabels": InclusiveDatesLabels;
        /**
          * @default false
         */
        "inline": boolean;
        /**
          * @default this.range     ? "Choose a date range (any way you like)"     : "Choose a date (any way you like)"
         */
        "label": string;
        /**
          * @default navigator?.language || "en-US"
         */
        "locale": string;
        "maxDate"?: string;
        "minDate"?: string;
        "nextMonthButtonContent"?: string;
        "nextYearButtonContent"?: string;
        "parseDate": (text: string, shouldSetValue?: boolean, chronoOptions?: ChronoOptions | undefined) => Promise<ChronoParsedDateString>;
        /**
          * @default this.range     ? `Try "June 8 to 12"`     : `Try "tomorrrow" or "in ten days"`
         */
        "placeholder": string;
        /**
          * @default this.range     ? ["Monday to Wednesday", "July 5 to 10"]     : ["Yesterday", "Today", "Tomorrow", "In 10 days"]
         */
        "quickButtons": string[];
        /**
          * @default false
         */
        "range"?: boolean;
        /**
          * @default getISODateString(new Date())
         */
        "referenceDate": string;
        /**
          * @default true
         */
        "showClearButton": boolean;
        /**
          * @default false
         */
        "showKeyboardHint": boolean;
        /**
          * @default true
         */
        "showMonthStepper": boolean;
        /**
          * @default true
         */
        "showQuickButtons": boolean;
        /**
          * @default true
         */
        "showTodayButton": boolean;
        /**
          * @default false
         */
        "showYearStepper": boolean;
        /**
          * @default getISODateString(new Date())
         */
        "startDate": string;
        "todayButtonContent"?: string;
        /**
          * @default false
         */
        "useStrictDateParsing": boolean;
        "value"?: string | string[];
    }
    interface InclusiveDatesCalendar {
        "clearButtonContent"?: string;
        /**
          * @default () => false
         */
        "disableDate": (date: Date) => boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default "inclusive-dates-calendar"
         */
        "elementClassName": string;
        /**
          * @default 0
         */
        "firstDayOfWeek": number;
        /**
          * @default false
         */
        "inline": boolean;
        /**
          * @default defaultLabels
         */
        "labels": InclusiveDatesCalendarLabels1;
        /**
          * @default navigator?.language || "en-US"
         */
        "locale"?: string;
        "maxDate"?: string;
        "minDate"?: string;
        /**
          * @default false
         */
        "modalIsOpen"?: boolean;
        "nextMonthButtonContent"?: string;
        "nextYearButtonContent"?: string;
        "previousMonthButtonContent"?: string;
        "previousYearButtonContent"?: string;
        /**
          * @default false
         */
        "range"?: boolean;
        /**
          * @default false
         */
        "showClearButton"?: boolean;
        /**
          * @default true
         */
        "showHiddenTitle"?: boolean;
        /**
          * @default false
         */
        "showKeyboardHint"?: boolean;
        /**
          * @default true
         */
        "showMonthStepper"?: boolean;
        /**
          * @default true
         */
        "showTodayButton"?: boolean;
        /**
          * @default false
         */
        "showYearStepper"?: boolean;
        /**
          * @default getISODateString(new Date())
         */
        "startDate"?: string;
        "todayButtonContent"?: string;
        "value"?: Date | Date[] | null;
    }
    interface InclusiveDatesModal {
        /**
          * Close the dialog.
         */
        "close": () => Promise<void>;
        "getState": () => Promise<boolean>;
        /**
          * @default false
         */
        "inline"?: boolean;
        "label": string;
        /**
          * Open the dialog.
         */
        "open": () => Promise<void>;
        "setTriggerElement": (element: HTMLElement) => Promise<void>;
    }
    interface InclusiveTimes {
        "calendarButtonContent"?: string;
        "clearValue": () => Promise<void>;
        /**
          * @default () => false
         */
        "disableDate": (date: Date) => boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default "inclusive-times"
         */
        "elementClassName"?: string;
        /**
          * @default 1
         */
        "firstDayOfWeek"?: number;
        /**
          * @default "YYYY-MM-DDTHH:mm:ss"
         */
        "format": string;
        /**
          * @default false
         */
        "hasError": boolean;
        "id": string;
        "inclusiveDatesCalendarLabels"?: InclusiveDatesCalendarLabels;
        /**
          * @default defaultLabels
         */
        "inclusiveTimesLabels": InclusiveTimesLabels;
        /**
          * @default false
         */
        "inline": boolean;
        /**
          * @default "Choose a date and time"
         */
        "label": string;
        /**
          * @default navigator?.language || "en-US"
         */
        "locale": string;
        "maxDate"?: string;
        "minDate"?: string;
        /**
          * @default "Try \"tomorrow at 3pm\""
         */
        "placeholder": string;
        /**
          * @default false
         */
        "range"?: boolean;
        /**
          * @default getISODateString(new Date())
         */
        "referenceDate": string;
        /**
          * @default true
         */
        "showClearButton": boolean;
        /**
          * @default true
         */
        "showMonthStepper": boolean;
        /**
          * @default true
         */
        "showTodayButton": boolean;
        /**
          * @default false
         */
        "showYearStepper": boolean;
        /**
          * @default getISODateString(new Date())
         */
        "startDate": string;
        /**
          * @default true
         */
        "use12HourFormat": boolean;
        "value"?: string | string[];
    }
    interface InclusiveTimesPicker {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default "inclusive-times-picker"
         */
        "elementClassName": string;
        /**
          * @default 12
         */
        "hours": number;
        /**
          * @default defaultLabels
         */
        "labels": InclusivekTimesPickerLabels;
        /**
          * @default true
         */
        "labelsSrOnly": boolean;
        /**
          * @default 0
         */
        "minutes": number;
        /**
          * @default false
         */
        "use12HourFormat": boolean;
    }
}
export interface InclusiveDatesCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLInclusiveDatesElement;
}
export interface InclusiveDatesCalendarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLInclusiveDatesCalendarElement;
}
export interface InclusiveDatesModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLInclusiveDatesModalElement;
}
export interface InclusiveTimesCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLInclusiveTimesElement;
}
export interface InclusiveTimesPickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLInclusiveTimesPickerElement;
}
declare global {
    interface HTMLInclusiveDatesElementEventMap {
        "selectDate": string | string[] | undefined;
        "changeYear": YearChangedEventDetails;
        "componentReady": void;
    }
    interface HTMLInclusiveDatesElement extends Components.InclusiveDates, HTMLStencilElement {
        addEventListener<K extends keyof HTMLInclusiveDatesElementEventMap>(type: K, listener: (this: HTMLInclusiveDatesElement, ev: InclusiveDatesCustomEvent<HTMLInclusiveDatesElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLInclusiveDatesElementEventMap>(type: K, listener: (this: HTMLInclusiveDatesElement, ev: InclusiveDatesCustomEvent<HTMLInclusiveDatesElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLInclusiveDatesElement: {
        prototype: HTMLInclusiveDatesElement;
        new (): HTMLInclusiveDatesElement;
    };
    interface HTMLInclusiveDatesCalendarElementEventMap {
        "selectDate": string | string[] | undefined;
        "changeMonth": MonthChangedEventDetails;
        "changeYear": YearChangedEventDetails1;
    }
    interface HTMLInclusiveDatesCalendarElement extends Components.InclusiveDatesCalendar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLInclusiveDatesCalendarElementEventMap>(type: K, listener: (this: HTMLInclusiveDatesCalendarElement, ev: InclusiveDatesCalendarCustomEvent<HTMLInclusiveDatesCalendarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLInclusiveDatesCalendarElementEventMap>(type: K, listener: (this: HTMLInclusiveDatesCalendarElement, ev: InclusiveDatesCalendarCustomEvent<HTMLInclusiveDatesCalendarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLInclusiveDatesCalendarElement: {
        prototype: HTMLInclusiveDatesCalendarElement;
        new (): HTMLInclusiveDatesCalendarElement;
    };
    interface HTMLInclusiveDatesModalElementEventMap {
        "opened": any;
        "closed": any;
    }
    interface HTMLInclusiveDatesModalElement extends Components.InclusiveDatesModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLInclusiveDatesModalElementEventMap>(type: K, listener: (this: HTMLInclusiveDatesModalElement, ev: InclusiveDatesModalCustomEvent<HTMLInclusiveDatesModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLInclusiveDatesModalElementEventMap>(type: K, listener: (this: HTMLInclusiveDatesModalElement, ev: InclusiveDatesModalCustomEvent<HTMLInclusiveDatesModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLInclusiveDatesModalElement: {
        prototype: HTMLInclusiveDatesModalElement;
        new (): HTMLInclusiveDatesModalElement;
    };
    interface HTMLInclusiveTimesElementEventMap {
        "selectDateTime": string | string[] | undefined;
        "changeYear": YearChangedEventDetails;
        "componentReady": void;
    }
    interface HTMLInclusiveTimesElement extends Components.InclusiveTimes, HTMLStencilElement {
        addEventListener<K extends keyof HTMLInclusiveTimesElementEventMap>(type: K, listener: (this: HTMLInclusiveTimesElement, ev: InclusiveTimesCustomEvent<HTMLInclusiveTimesElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLInclusiveTimesElementEventMap>(type: K, listener: (this: HTMLInclusiveTimesElement, ev: InclusiveTimesCustomEvent<HTMLInclusiveTimesElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLInclusiveTimesElement: {
        prototype: HTMLInclusiveTimesElement;
        new (): HTMLInclusiveTimesElement;
    };
    interface HTMLInclusiveTimesPickerElementEventMap {
        "timeChanged": TimeValue;
    }
    interface HTMLInclusiveTimesPickerElement extends Components.InclusiveTimesPicker, HTMLStencilElement {
        addEventListener<K extends keyof HTMLInclusiveTimesPickerElementEventMap>(type: K, listener: (this: HTMLInclusiveTimesPickerElement, ev: InclusiveTimesPickerCustomEvent<HTMLInclusiveTimesPickerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLInclusiveTimesPickerElementEventMap>(type: K, listener: (this: HTMLInclusiveTimesPickerElement, ev: InclusiveTimesPickerCustomEvent<HTMLInclusiveTimesPickerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLInclusiveTimesPickerElement: {
        prototype: HTMLInclusiveTimesPickerElement;
        new (): HTMLInclusiveTimesPickerElement;
    };
    interface HTMLElementTagNameMap {
        "inclusive-dates": HTMLInclusiveDatesElement;
        "inclusive-dates-calendar": HTMLInclusiveDatesCalendarElement;
        "inclusive-dates-modal": HTMLInclusiveDatesModalElement;
        "inclusive-times": HTMLInclusiveTimesElement;
        "inclusive-times-picker": HTMLInclusiveTimesPickerElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface InclusiveDates {
        "calendarButtonContent"?: string;
        /**
          * @default () =>     false
         */
        "disableDate"?: HTMLInclusiveDatesCalendarElement["disableDate"];
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default "inclusive-dates"
         */
        "elementClassName"?: string;
        /**
          * @default 1
         */
        "firstDayOfWeek"?: number;
        /**
          * @default "YYYY-MM-DD"
         */
        "format"?: string;
        /**
          * @default true
         */
        "formatInputOnAccept"?: boolean;
        /**
          * @default false
         */
        "hasError"?: boolean;
        "id": string;
        "inclusiveDatesCalendarLabels"?: InclusiveDatesCalendarLabels;
        /**
          * @default defaultLabels
         */
        "inclusiveDatesLabels"?: InclusiveDatesLabels;
        /**
          * @default false
         */
        "inline"?: boolean;
        /**
          * @default this.range     ? "Choose a date range (any way you like)"     : "Choose a date (any way you like)"
         */
        "label"?: string;
        /**
          * @default navigator?.language || "en-US"
         */
        "locale"?: string;
        "maxDate"?: string;
        "minDate"?: string;
        "nextMonthButtonContent"?: string;
        "nextYearButtonContent"?: string;
        "onChangeYear"?: (event: InclusiveDatesCustomEvent<YearChangedEventDetails>) => void;
        "onComponentReady"?: (event: InclusiveDatesCustomEvent<void>) => void;
        "onSelectDate"?: (event: InclusiveDatesCustomEvent<string | string[] | undefined>) => void;
        /**
          * @default this.range     ? `Try "June 8 to 12"`     : `Try "tomorrrow" or "in ten days"`
         */
        "placeholder"?: string;
        /**
          * @default this.range     ? ["Monday to Wednesday", "July 5 to 10"]     : ["Yesterday", "Today", "Tomorrow", "In 10 days"]
         */
        "quickButtons"?: string[];
        /**
          * @default false
         */
        "range"?: boolean;
        /**
          * @default getISODateString(new Date())
         */
        "referenceDate"?: string;
        /**
          * @default true
         */
        "showClearButton"?: boolean;
        /**
          * @default false
         */
        "showKeyboardHint"?: boolean;
        /**
          * @default true
         */
        "showMonthStepper"?: boolean;
        /**
          * @default true
         */
        "showQuickButtons"?: boolean;
        /**
          * @default true
         */
        "showTodayButton"?: boolean;
        /**
          * @default false
         */
        "showYearStepper"?: boolean;
        /**
          * @default getISODateString(new Date())
         */
        "startDate"?: string;
        "todayButtonContent"?: string;
        /**
          * @default false
         */
        "useStrictDateParsing"?: boolean;
        "value"?: string | string[];
    }
    interface InclusiveDatesCalendar {
        "clearButtonContent"?: string;
        /**
          * @default () => false
         */
        "disableDate"?: (date: Date) => boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default "inclusive-dates-calendar"
         */
        "elementClassName"?: string;
        /**
          * @default 0
         */
        "firstDayOfWeek"?: number;
        /**
          * @default false
         */
        "inline"?: boolean;
        /**
          * @default defaultLabels
         */
        "labels"?: InclusiveDatesCalendarLabels1;
        /**
          * @default navigator?.language || "en-US"
         */
        "locale"?: string;
        "maxDate"?: string;
        "minDate"?: string;
        /**
          * @default false
         */
        "modalIsOpen"?: boolean;
        "nextMonthButtonContent"?: string;
        "nextYearButtonContent"?: string;
        "onChangeMonth"?: (event: InclusiveDatesCalendarCustomEvent<MonthChangedEventDetails>) => void;
        "onChangeYear"?: (event: InclusiveDatesCalendarCustomEvent<YearChangedEventDetails1>) => void;
        "onSelectDate"?: (event: InclusiveDatesCalendarCustomEvent<string | string[] | undefined>) => void;
        "previousMonthButtonContent"?: string;
        "previousYearButtonContent"?: string;
        /**
          * @default false
         */
        "range"?: boolean;
        /**
          * @default false
         */
        "showClearButton"?: boolean;
        /**
          * @default true
         */
        "showHiddenTitle"?: boolean;
        /**
          * @default false
         */
        "showKeyboardHint"?: boolean;
        /**
          * @default true
         */
        "showMonthStepper"?: boolean;
        /**
          * @default true
         */
        "showTodayButton"?: boolean;
        /**
          * @default false
         */
        "showYearStepper"?: boolean;
        /**
          * @default getISODateString(new Date())
         */
        "startDate"?: string;
        "todayButtonContent"?: string;
        "value"?: Date | Date[] | null;
    }
    interface InclusiveDatesModal {
        /**
          * @default false
         */
        "inline"?: boolean;
        "label": string;
        "onClosed"?: (event: InclusiveDatesModalCustomEvent<any>) => void;
        "onOpened"?: (event: InclusiveDatesModalCustomEvent<any>) => void;
    }
    interface InclusiveTimes {
        "calendarButtonContent"?: string;
        /**
          * @default () => false
         */
        "disableDate"?: (date: Date) => boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default "inclusive-times"
         */
        "elementClassName"?: string;
        /**
          * @default 1
         */
        "firstDayOfWeek"?: number;
        /**
          * @default "YYYY-MM-DDTHH:mm:ss"
         */
        "format"?: string;
        /**
          * @default false
         */
        "hasError"?: boolean;
        "id": string;
        "inclusiveDatesCalendarLabels"?: InclusiveDatesCalendarLabels;
        /**
          * @default defaultLabels
         */
        "inclusiveTimesLabels"?: InclusiveTimesLabels;
        /**
          * @default false
         */
        "inline"?: boolean;
        /**
          * @default "Choose a date and time"
         */
        "label"?: string;
        /**
          * @default navigator?.language || "en-US"
         */
        "locale"?: string;
        "maxDate"?: string;
        "minDate"?: string;
        "onChangeYear"?: (event: InclusiveTimesCustomEvent<YearChangedEventDetails>) => void;
        "onComponentReady"?: (event: InclusiveTimesCustomEvent<void>) => void;
        "onSelectDateTime"?: (event: InclusiveTimesCustomEvent<string | string[] | undefined>) => void;
        /**
          * @default "Try \"tomorrow at 3pm\""
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "range"?: boolean;
        /**
          * @default getISODateString(new Date())
         */
        "referenceDate"?: string;
        /**
          * @default true
         */
        "showClearButton"?: boolean;
        /**
          * @default true
         */
        "showMonthStepper"?: boolean;
        /**
          * @default true
         */
        "showTodayButton"?: boolean;
        /**
          * @default false
         */
        "showYearStepper"?: boolean;
        /**
          * @default getISODateString(new Date())
         */
        "startDate"?: string;
        /**
          * @default true
         */
        "use12HourFormat"?: boolean;
        "value"?: string | string[];
    }
    interface InclusiveTimesPicker {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default "inclusive-times-picker"
         */
        "elementClassName"?: string;
        /**
          * @default 12
         */
        "hours"?: number;
        /**
          * @default defaultLabels
         */
        "labels"?: InclusivekTimesPickerLabels;
        /**
          * @default true
         */
        "labelsSrOnly"?: boolean;
        /**
          * @default 0
         */
        "minutes"?: number;
        "onTimeChanged"?: (event: InclusiveTimesPickerCustomEvent<TimeValue>) => void;
        /**
          * @default false
         */
        "use12HourFormat"?: boolean;
    }

    interface InclusiveDatesAttributes {
        "id": string;
        "value": string | string[];
        "range": boolean;
        "label": string;
        "placeholder": string;
        "locale": string;
        "disabled": boolean;
        "minDate": string;
        "maxDate": string;
        "startDate": string;
        "referenceDate": string;
        "useStrictDateParsing": boolean;
        "inline": boolean;
        "hasError": boolean;
        "nextMonthButtonContent": string;
        "nextYearButtonContent": string;
        "showYearStepper": boolean;
        "showMonthStepper": boolean;
        "showClearButton": boolean;
        "showTodayButton": boolean;
        "formatInputOnAccept": boolean;
        "showKeyboardHint": boolean;
        "elementClassName": string;
        "firstDayOfWeek": number;
        "format": string;
        "todayButtonContent": string;
        "calendarButtonContent": string;
        "showQuickButtons": boolean;
    }
    interface InclusiveDatesCalendarAttributes {
        "clearButtonContent": string;
        "disabled": boolean;
        "modalIsOpen": boolean;
        "elementClassName": string;
        "firstDayOfWeek": number;
        "range": boolean;
        "locale": string;
        "nextMonthButtonContent": string;
        "nextYearButtonContent": string;
        "previousMonthButtonContent": string;
        "previousYearButtonContent": string;
        "minDate": string;
        "maxDate": string;
        "inline": boolean;
        "showClearButton": boolean;
        "showMonthStepper": boolean;
        "showTodayButton": boolean;
        "showYearStepper": boolean;
        "showKeyboardHint": boolean;
        "showHiddenTitle": boolean;
        "startDate": string;
        "todayButtonContent": string;
    }
    interface InclusiveDatesModalAttributes {
        "label": string;
        "inline": boolean;
    }
    interface InclusiveTimesAttributes {
        "id": string;
        "value": string | string[];
        "range": boolean;
        "label": string;
        "placeholder": string;
        "locale": string;
        "disabled": boolean;
        "minDate": string;
        "maxDate": string;
        "startDate": string;
        "referenceDate": string;
        "use12HourFormat": boolean;
        "inline": boolean;
        "hasError": boolean;
        "showYearStepper": boolean;
        "showMonthStepper": boolean;
        "showClearButton": boolean;
        "showTodayButton": boolean;
        "calendarButtonContent": string;
        "elementClassName": string;
        "firstDayOfWeek": number;
        "format": string;
    }
    interface InclusiveTimesPickerAttributes {
        "hours": number;
        "minutes": number;
        "use12HourFormat": boolean;
        "labelsSrOnly": boolean;
        "disabled": boolean;
        "elementClassName": string;
    }

    interface IntrinsicElements {
        "inclusive-dates": Omit<InclusiveDates, keyof InclusiveDatesAttributes> & { [K in keyof InclusiveDates & keyof InclusiveDatesAttributes]?: InclusiveDates[K] } & { [K in keyof InclusiveDates & keyof InclusiveDatesAttributes as `attr:${K}`]?: InclusiveDatesAttributes[K] } & { [K in keyof InclusiveDates & keyof InclusiveDatesAttributes as `prop:${K}`]?: InclusiveDates[K] } & OneOf<"id", InclusiveDates["id"], InclusiveDatesAttributes["id"]>;
        "inclusive-dates-calendar": Omit<InclusiveDatesCalendar, keyof InclusiveDatesCalendarAttributes> & { [K in keyof InclusiveDatesCalendar & keyof InclusiveDatesCalendarAttributes]?: InclusiveDatesCalendar[K] } & { [K in keyof InclusiveDatesCalendar & keyof InclusiveDatesCalendarAttributes as `attr:${K}`]?: InclusiveDatesCalendarAttributes[K] } & { [K in keyof InclusiveDatesCalendar & keyof InclusiveDatesCalendarAttributes as `prop:${K}`]?: InclusiveDatesCalendar[K] };
        "inclusive-dates-modal": Omit<InclusiveDatesModal, keyof InclusiveDatesModalAttributes> & { [K in keyof InclusiveDatesModal & keyof InclusiveDatesModalAttributes]?: InclusiveDatesModal[K] } & { [K in keyof InclusiveDatesModal & keyof InclusiveDatesModalAttributes as `attr:${K}`]?: InclusiveDatesModalAttributes[K] } & { [K in keyof InclusiveDatesModal & keyof InclusiveDatesModalAttributes as `prop:${K}`]?: InclusiveDatesModal[K] } & OneOf<"label", InclusiveDatesModal["label"], InclusiveDatesModalAttributes["label"]>;
        "inclusive-times": Omit<InclusiveTimes, keyof InclusiveTimesAttributes> & { [K in keyof InclusiveTimes & keyof InclusiveTimesAttributes]?: InclusiveTimes[K] } & { [K in keyof InclusiveTimes & keyof InclusiveTimesAttributes as `attr:${K}`]?: InclusiveTimesAttributes[K] } & { [K in keyof InclusiveTimes & keyof InclusiveTimesAttributes as `prop:${K}`]?: InclusiveTimes[K] } & OneOf<"id", InclusiveTimes["id"], InclusiveTimesAttributes["id"]>;
        "inclusive-times-picker": Omit<InclusiveTimesPicker, keyof InclusiveTimesPickerAttributes> & { [K in keyof InclusiveTimesPicker & keyof InclusiveTimesPickerAttributes]?: InclusiveTimesPicker[K] } & { [K in keyof InclusiveTimesPicker & keyof InclusiveTimesPickerAttributes as `attr:${K}`]?: InclusiveTimesPickerAttributes[K] } & { [K in keyof InclusiveTimesPicker & keyof InclusiveTimesPickerAttributes as `prop:${K}`]?: InclusiveTimesPicker[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "inclusive-dates": LocalJSX.IntrinsicElements["inclusive-dates"] & JSXBase.HTMLAttributes<HTMLInclusiveDatesElement>;
            "inclusive-dates-calendar": LocalJSX.IntrinsicElements["inclusive-dates-calendar"] & JSXBase.HTMLAttributes<HTMLInclusiveDatesCalendarElement>;
            "inclusive-dates-modal": LocalJSX.IntrinsicElements["inclusive-dates-modal"] & JSXBase.HTMLAttributes<HTMLInclusiveDatesModalElement>;
            "inclusive-times": LocalJSX.IntrinsicElements["inclusive-times"] & JSXBase.HTMLAttributes<HTMLInclusiveTimesElement>;
            "inclusive-times-picker": LocalJSX.IntrinsicElements["inclusive-times-picker"] & JSXBase.HTMLAttributes<HTMLInclusiveTimesPickerElement>;
        }
    }
}
